<?php

/**
 * Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    
 * @subpackage model
 * @author     Emanuele Gaspari
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle
{
	/**
	 * overrides of the setUp() method
	 */
	public function setUp()
	{ 
		parent::setUp();
		$this->actAs('Timestampable');
	}
	
	/**
	 * returns the relative filename of the cropped image
	 */
	public function getFotoFilenameCrop()
	{
		return 'crop_'.$this->getFotoFilename();
	}
	
	/**
	 * verifies the existence of the cropped file
	 */
	public function hasFileCrop()
	{
		if (file_exists(sfConfig::get('sf_upload_dir').'/'.$this->getFotoFilenameCrop()))
			return true;
		
		return false;
	}
	
	/**
	 * verifies if the article has the cropped image
	 */
	public function hasCrop()
	{
		if ($this->getFotoFilename() == '' || $this->isNew())
			return false;
		
		if (file_exists(sfConfig::get('sf_upload_dir').'/'.$this->getFotoFilenameCrop()))
			return true;
		
		return false;
	}
	
	/**
	 * prints the image tag of the cropped image
	 */
	public function getImageTagCrop()
	{
		echo image_tag('../uploads/'.$this->getFotoFilenameCrop());
	}
	
	/**
	 * returns a truncated portion of the description if $l < description length
	 * returns the entire text otherwise
	 * 
	 * @param unknown_type $l max length of text
	 */
	public function getDescriptionTruncate($l = null)
	{
		// default max length of truncated text
		if (!$l) $l = 100;
		
		if (strlen($this->getDescription()) > $l-3)
		{
			$str = substr($this->getDescription(), 0, $l-3).'...';
			return $str;
		}
		return $this->getDescription();
	}
	
	/**
	 * returns a truncated portion of the title if $l < title length
	 * returns the entire text otherwise
	 * 
	 * @param unknown_type $l max length of text
	 */
	public function getTitleTruncate($l = null)
	{
		// default max length of truncated text
		if (!$l) $l = 100;
		
		if (strlen($this->getTitle()) > $l-3)
		{
			$str = substr($this->getTitle(), 0, $l-3).'...';
			return $str;
		}
		return $this->getTitle();
	}
	
	/**
	 * before deleting an article, it deletes the related image and cropped image
	 * 
	 * @param Doctrine_Connection $conn
	 */
	public function delete(Doctrine_Connection $conn = null)
	{
		// deletes the image
		if ($this->hasFileCrop())
			unlink($this->getFotoFilenameCrop());
		
		// deletes the cropped image
		if (file_exists(sfConfig::get('sf_upload_dir').'/'.$this->getFotoFilename()))
			unlink($this->getFotoFilename());
		
		// calls parent to delete object
		parent::delete($conn);
	}
}