<?php

/**
 * ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
			return Doctrine_Core::getTable('Article');
    }
    
    /**
     * return the offers in the database, optionally limited by $max
     * 
     * @param unknown_type $max max number of items retrieved
     */
		public static function getOffers($max = null)
    {
    	$q = Doctrine_Core::getTable('Article')->createQuery()
    				->where('offers = ?', true)
    				->orderBy('order');
    						
			if ($max) $q->limit($max);
    	return $q->execute();
    }
    
    /**
     * return the promotions in the database, optionally limited by $max
     * 
     * @param unknown_type $max max number of items retrieved
     */
		public static function getPromotions($max = null)
    {
    	$q = Doctrine_Core::getTable('Article')->createQuery()
    				->where('promotions = ?', true)
    				->orderBy('order');
    						
			if ($max) $q->limit($max);
    	return $q->execute();
    }
}