all:
  .sf_guard_plugin_success_signin_url:
    sf_guard_plugin_success_signin_url: '@homepage'
    sf_guard_plugin_success_signout_url: '@homepage'
    
  offers_promotions:
    max_number: 3
    
  .emails:
    provider_email: provider@gmail.com
    
  .photos:
    photos_folder: photos
    max_num_uploaded_photos: 4
  .thumbnails:
    thumbnails_folder: thumbnails
    thumbnails_prefix: "thumb_"
    thumbnails_width: 100
    thumbnails_height: 100
  .users:
    users_folder: users
    
  .facebook:
    facebook_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    facebook_api_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    facebook_api_id: xxxxxxxxxxxxxxx
    
  .languages:
    available_interface_languages:
      en:
        code: en
        long_name: English
        flag_filename: gb.png
      it:
        code: it
        long_name: Italiano
        flag_filename: it.png
    folder_flag_interface_languages:    # relative to /web/images/
      flags_iso/24/