# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        XXXXXXXXX
    description:  xxx xxx xxx xxx
    keywords:     xxx, xxx, xxx
    language:     en
    robots:       index, follow

  stylesheets:
    - jquery.fileupload-ui.css
    - jquery.lightbox-0.5.css
    - ui-lightness/jquery-ui-1.8.11.custom.css
    - frontend.css

  javascripts:
    - jquery-1.5.1.min.js
    - jquery.lightbox-0.5.min.js
    - jquery-ui-1.8.11.custom.min.js
    - jquery.validate.min.js
    - localization/messages_it.js
    - tiny_mce/tiny_mce.js
    - jquery.equalheights.js
    - jquery.fileupload.js
    - jquery.fileupload-ui.js

    # javascript libraries websites    
    # equal heights: http://www.cssnewbie.com/equalheights-jquery-plugin/
    # validation: http://docs.jquery.com/Plugins/validation
    # qaptcha: http://www.myjqueryplugins.com/QapTcha
    # upload javascript: https://github.com/blueimp/jQuery-File-Upload

  has_layout:     true
  layout:         layout