# default english homepage
homepage:
  url:   /
  param: { module: default, action: index, culture: en_EN }

# localized homepage with filters on accepted languages
localized_homepage:
  url:   /:sf_culture/
  param: { module: default, action: index }
  requirements:
    sf_culture: (?:it|en)
    sf_slash: '\/?'

# url to change navigation language
change_language:
  url:   /change_language
  param: { module: default, action: changeLanguage }

# default page navigation
default:
  url:   /:sf_culture/:action/*
  param: {module: default }