<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    
 * @subpackage model
 * @author     Emanuele Gaspari
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
	/**
	 * returns the complete real name
	 * eg: "John Derrick"
	 */
	public function getFirstNameLastName()
	{
		return trim($this->getFirstName().' '.$this->getLastName());
	}
	
	/**
	 * overrides parent delete() method
	 * 
	 * before deleting a user from the database, deletes:
	 *  - avatar + thumbnail
	 *  - photo + thumbnail
	 *  - relative thumbnails
	 *  - user profile
	 * 
	 * @param Doctrine_Connection $conn
	 */
	public function delete(Doctrine_Connection $conn = null)
	{
		// delete avatar
		$filename_avatar = sfConfig::get('sf_upload_dir').'/'.sfConfig::get('app_users_folder').'/'.$this->Profile->getAvatar();
		if (file_exists($filename_avatar))
			unlink($filename_avatar);
		// delete avatar thumbnail
		$filename_avatar_thumbnail = sfConfig::get('sf_upload_dir').'/'.sfConfig::get('app_thumbnails_folder').'/'.sfConfig::get('app_thumbnails_prefix').$this->Profile->getAvatar();
		if (file_exists($filename_avatar_thumbnail))
			unlink($filename_avatar_thumbnail);
		
		// delete photo
		$filename_foto = sfConfig::get('sf_upload_dir').'/'.sfConfig::get('app_users_folder').'/'.$this->Profile->getFoto();
		if (file_exists($filename_foto))
			unlink($filename_foto);
		// delete photo thumbnail
		$filename_foto_thumbnail = sfConfig::get('sf_upload_dir').'/'.sfConfig::get('app_thumbnails_folder').'/'.sfConfig::get('app_thumbnails_prefix').$this->Profile->getFoto();
		if (file_exists($filename_foto_thumbnail))
			unlink($filename_foto_thumbnail);
		
		// delete the profile
			$profile = $this->Profile;
			if ($profile)
				$profile->delete();
		
		parent::delete($conn);
	}
}